#ifndef PARTICLE_H
#define PARTICLE_H
#include "vectortools.h"

#define SCALE 10e-5 //replace with global const in some header someday

class Particle 
{
private:
	std::string name_m;
	int* window_m; //change the type once you know how and have one defined
	int* pic_m; //change the type once you know how and have one defined
	double charge_m;
	double mass_m;
	dblArray3_t position_m;
	dblArray3_t velocity_m;
	double qOVERm_m;

	void updV(const dblArray3_t& b, double dt);

public:
	Particle(double charge, double mass, dblArray3_t& position, dblArray3_t& velocity, std::string name = "", int* window = nullptr, int* pic = nullptr)
		: charge_m{ charge }, mass_m{ mass }, position_m(position), velocity_m(velocity), name_m{ name }, window_m{ window }, pic_m{ pic }, qOVERm_m{ charge / mass } {}
	
	dblArray3_t updP(const dblArray3_t& b, double dt);
	dblArray3_t calcBatP(const dblArray3_t p); //Mag field generated by moving charged particle
	//dblArray3_t foRKvCrossB(const dblArray3_t& B, double dt); //Fourth Order Runge Kutta, to be added perhaps at a later date
};

#endif
